/* eslint-disable no-console */
import * as fs from "fs";
import * as path from "path";

const LAYERS = [
  "dense1",
  "dense2",
  "mp",
  "moveHead1",
  "moveHead2",
  "passHead1",
  "passHead2",
] as const;

/**
 * Pick a checkpoint to bake. CLI arg wins; otherwise prefer selfPlay-latest
 * over warmStart.
 */
function resolveCheckpoint(): string {
  if (process.argv[2]) return path.resolve(process.argv[2]);
  const ckptDir = path.resolve(__dirname, "checkpoints");
  const latest = path.join(ckptDir, "selfPlay-latest.json");
  const warm = path.join(ckptDir, "warmStart.json");
  if (fs.existsSync(latest)) return latest;
  if (fs.existsSync(warm)) return warm;
  throw new Error(
    "no checkpoint found in training/checkpoints; run wotd:warmstart first",
  );
}

const inPath = resolveCheckpoint();
const outPath = path.resolve(__dirname, "..", "model", "weights.ts");
const raw = JSON.parse(fs.readFileSync(inPath, "utf8"));

const relIn = path.relative(path.dirname(outPath), inPath);

let out = `// Auto-generated by training/bake.ts — do not edit by hand.\n`;
out += `// Source: ${relIn}\n\n`;
out += `import type { ModelWeights } from "./forward.ts";\n\n`;

for (const layer of LAYERS) {
  const { W, b } = raw[layer];
  out += `const ${layer}_W = new Float32Array([${W.join(",")}]);\n`;
  out += `const ${layer}_b = new Float32Array([${b.join(",")}]);\n`;
}

out += `\n/** Trained weights baked at build time; loaded by the browser AI. */\n`;
out += `export const BAKED_WEIGHTS: ModelWeights = {\n`;
for (const layer of LAYERS) {
  out += `  ${layer}: { W: ${layer}_W, b: ${layer}_b },\n`;
}
out += `};\n`;

fs.writeFileSync(outPath, out);
const bytes = fs.statSync(outPath).size;
console.log(
  `wrote ${path.relative(process.cwd(), outPath)} (${(bytes / 1024).toFixed(1)}KB) from ${path.basename(inPath)}`,
);
