/* eslint-disable no-console */
import * as fs from "fs";
import * as path from "path";
import { LAYER_NAMES } from "../model/forward.ts";
import { resolveCheckpoint } from "./util.ts";

const inPath = resolveCheckpoint({
  override: process.argv[2],
  ckptDir: path.resolve(__dirname, "checkpoints"),
  candidates: ["value-latest.json"],
});
const outPath = path.resolve(__dirname, "..", "model", "weights.ts");
const raw = JSON.parse(fs.readFileSync(inPath, "utf8"));

const relIn = path.relative(path.dirname(outPath), inPath);

let out = `// Auto-generated by training/bake.ts — do not edit by hand.\n`;
out += `// Source: ${relIn}\n\n`;
out += `import type { ModelWeights } from "./forward.ts";\n\n`;

for (const layer of LAYER_NAMES) {
  const { W, b } = raw[layer];
  out += `const ${layer}_W = new Float32Array([${W.join(",")}]);\n`;
  out += `const ${layer}_b = new Float32Array([${b.join(",")}]);\n`;
}

out += `\n/** Trained weights baked at build time; loaded by the browser AI. */\n`;
out += `export const BAKED_WEIGHTS: ModelWeights = {\n`;
for (const layer of LAYER_NAMES) {
  out += `  ${layer}: { W: ${layer}_W, b: ${layer}_b },\n`;
}
out += `};\n`;

fs.writeFileSync(outPath, out);
const bytes = fs.statSync(outPath).size;
console.log(
  `wrote ${path.relative(process.cwd(), outPath)} (${(bytes / 1024).toFixed(1)}KB) from ${path.basename(inPath)}`,
);
