// English contractions mapped to their US General American pronunciation,
// written in ARPABET (see SHAVIAN_TO_ARPABET in shavianating.js).
// "+" marks compound letters. Keys are lowercase with straight apostrophes.
export const CONTRACTIONS = {
  // n't
  "ain't": "EY N T",
  "aren't": "AA+R N T",
  "can't": "K AE N T",
  "couldn't": "K UH D AX N T",
  "didn't": "D IH D AX N T",
  "doesn't": "D AH Z AX N T",
  "don't": "D OW N T",
  "hadn't": "HH AE D AX N T",
  "hasn't": "HH AE Z AX N T",
  "haven't": "HH AE V AX N T",
  "isn't": "IH Z AX N T",
  "mightn't": "M AY T AX N T",
  "mustn't": "M AH S AX N T",
  "needn't": "N IY D AX N T",
  "oughtn't": "AO T AX N T",
  "shan't": "SH AE N T",
  "shouldn't": "SH UH D AX N T",
  "wasn't": "W AA Z AX N T",
  "weren't": "W ER N T",
  "won't": "W OW N T",
  "wouldn't": "W UH D AX N T",

  // personal pronouns
  "i'm": "AY M",
  "i've": "AY V",
  "i'll": "AY L",
  "i'd": "AY D",
  "you're": "Y+UW AX+R",
  "you've": "Y+UW V",
  "you'll": "Y+UW L",
  "you'd": "Y+UW D",
  "he's": "HH IY Z",
  "he'll": "HH IY L",
  "he'd": "HH IY D",
  "she's": "SH IY Z",
  "she'll": "SH IY L",
  "she'd": "SH IY D",
  "it's": "IH T S",
  "it'll": "IH T AX L",
  "it'd": "IH T AX D",
  "we're": "W IH+R",
  "we've": "W IY V",
  "we'll": "W IY L",
  "we'd": "W IY D",
  "they're": "DH EH+R",
  "they've": "DH EY V",
  "they'll": "DH EY L",
  "they'd": "DH EY D",

  // question words
  "who's": "HH UW Z",
  "who're": "HH UW AX+R",
  "who've": "HH UW V",
  "who'll": "HH UW L",
  "who'd": "HH UW D",
  "what's": "W AA T S",
  "what're": "W AA T AX+R",
  "what've": "W AA T AX V",
  "what'll": "W AA T AX L",
  "what'd": "W AA T AX D",
  "where's": "W EH+R Z",
  "where'd": "W EH+R D",
  "where've": "W EH+R AX V",
  "where'll": "W EH+R AX L",
  "when's": "W EH N Z",
  "when'd": "W EH N D",
  "why's": "W AY Z",
  "why'd": "W AY D",
  "how's": "HH AW Z",
  "how'd": "HH AW D",
  "how'll": "HH AW L",

  // demonstratives & existentials
  "that's": "DH AE T S",
  "that'll": "DH AE T AX L",
  "that'd": "DH AE T AX D",
  "this'll": "DH IH S AX L",
  "there's": "DH EH+R Z",
  "there're": "DH EH+R AX+R",
  "there'll": "DH EH+R AX L",
  "there'd": "DH EH+R AX D",
  "there've": "DH EH+R AX V",
  "here's": "HH IH+R Z",
  "let's": "L EH T S",

  // modal + 've
  "could've": "K UH D AX V",
  "should've": "SH UH D AX V",
  "would've": "W UH D AX V",
  "might've": "M AY T AX V",
  "must've": "M AH S T AX V",
  "couldn't've": "K UH D AX N T AX V",
  "shouldn't've": "SH UH D AX N T AX V",
  "wouldn't've": "W UH D AX N T AX V",

  // everything else
  "o'clock": "AX K L AA K",
  "ma'am": "M AE M",
  "y'all": "Y AO L",
  "'em": "AX M",
  "'tis": "T IH Z",
  "'twas": "T W AH Z",
  "'cause": "K AH Z",
  "'til": "T IH L",
  "ne'er": "N EH+R",
  "o'er": "AO+R",
  "e'er": "EH+R",
};
